"""INFRA_REPORT.md: the plain-English account of what Cirdan found."""

from __future__ import annotations

from cirdan.access.context import AccessContext
from cirdan.access.redaction import redact_text
from cirdan.fingerprint.engine import Fingerprint
from cirdan.graph.diff import Finding
from cirdan.graph.queries import GraphQueries
from cirdan.graph.schema import Confidence, Origin
from cirdan.graph.store import GraphStore
from cirdan.util import now_iso

_SEVERITY_ICONS = {"critical": "🔴", "warning": "🟡", "info": "🔵"}


def build_infra_report(
    store: GraphStore,
    fingerprint: Fingerprint,
    access: AccessContext,
    findings: list[Finding],
    incidents: list[dict] | None = None,
    communities: dict | None = None,
) -> str:
    queries = GraphQueries(store)
    nodes = store.all_nodes()
    edges = store.all_edges()
    lines: list[str] = []
    add = lines.append

    add("# Infrastructure Report")
    add("")
    add(f"Generated by Cirdan at {now_iso()}.")
    add("")

    # -- fingerprint ---------------------------------------------------------
    add("## What this system is")
    add("")
    add(f"- **Primary runtime:** {fingerprint.primary_runtime or 'unknown'}")
    add(f"- **Primary cloud:** {fingerprint.primary_cloud or 'none detected'}")
    if fingerprint.iac:
        add(f"- **Infrastructure as code:** {', '.join(fingerprint.iac)}")
    if fingerprint.telemetry:
        add(f"- **Telemetry:** {', '.join(fingerprint.telemetry)}")
    add("")
    add("| Detected system | Confidence | Strongest evidence |")
    add("|---|---|---|")
    for det in fingerprint.detected_systems:
        evidence = redact_text(det.evidence[0]) if det.evidence else ""
        add(f"| {det.type} | {int(det.confidence * 100)}% | {evidence} |")
    add("")

    # -- access ----------------------------------------------------------------
    add("## What Cirdan can currently access")
    add("")
    caps = access.capabilities
    granted = sorted(k for k, v in caps.items() if v)
    denied = sorted(k for k, v in caps.items() if not v)
    add(f"Running as `{access.source.get('agent', 'unknown')}` with inherited session access.")
    add("")
    add(f"- Available: {', '.join(f'`{c}`' for c in granted) or 'nothing'}")
    add(f"- Not available: {', '.join(f'`{c}`' for c in denied) or 'nothing'}")
    add("")

    # -- inventory ---------------------------------------------------------------
    add("## Services and components")
    add("")
    add(f"Graph contains **{len(nodes)} nodes** and **{len(edges)} edges**.")
    add("")
    add("| Component | Type | Origin | State | Direct dependencies |")
    add("|---|---|---|---|---|")
    interesting = [
        n for n in nodes
        if n.type in {"Service", "Database", "Cache", "Queue", "LoadBalancer", "SystemdUnit", "Bucket"}
    ]
    for node in sorted(interesting, key=lambda n: (n.type, n.name)):
        deps = queries.dependencies(node.id, max_depth=1)
        dep_names = ", ".join(d["node"].name for d in deps) or "—"
        state = node.attrs.get("health") or node.attrs.get("state") or "—"
        add(f"| {node.name} | {node.type} | {node.origin.value} | {state} | {dep_names} |")
    add("")

    # -- subsystems (louvain communities) ----------------------------------------
    if communities:
        groups: dict[int, list] = {}
        node_by_id = {n.id: n for n in nodes}
        for node_id, community in communities.items():
            node = node_by_id.get(node_id)
            if node:
                groups.setdefault(community, []).append(node)
        multi = {c: members for c, members in groups.items() if len(members) >= 2}
        if multi:
            add("## Subsystems")
            add("")
            add("Connected groups detected in the topology (Louvain clustering):")
            add("")
            for community, members in sorted(multi.items(), key=lambda kv: -len(kv[1]))[:8]:
                names = ", ".join(sorted(m.name for m in members)[:10])
                more = f" (+{len(members) - 10} more)" if len(members) > 10 else ""
                add(f"- **Subsystem {community}** ({len(members)} components): {names}{more}")
            add("")
        # The graph's hubs: what the most things depend on.
        degree: dict[str, int] = {}
        for edge in edges:
            degree[edge.source] = degree.get(edge.source, 0) + 1
            degree[edge.target] = degree.get(edge.target, 0) + 1
        hubs = sorted(
            (n for n in nodes if degree.get(n.id, 0) >= 3),
            key=lambda n: -degree.get(n.id, 0),
        )[:5]
        if hubs:
            add("Highly connected hubs: " + ", ".join(
                f"**{h.name}** ({degree[h.id]} edges)" for h in hubs))
            add("")

    # -- entrypoints -----------------------------------------------------------
    entrypoints = queries.public_entrypoints()
    add("## Public entry points")
    add("")
    if entrypoints:
        for entry in entrypoints:
            add(f"- **{entry['node'].name}** ({entry['node'].type}): {'; '.join(entry['reasons'])}")
    else:
        add("None detected.")
    add("")

    # -- drift -------------------------------------------------------------------
    add("## Drift and findings")
    add("")
    if findings:
        for finding in sorted(findings, key=lambda f: ("critical", "warning", "info").index(f.severity)):
            icon = _SEVERITY_ICONS.get(finding.severity, "")
            add(f"- {icon} **{finding.kind}**: {redact_text(finding.summary)}")
    else:
        add("No drift between declared and observed infrastructure.")
    add("")

    # -- incidents -----------------------------------------------------------------
    if incidents:
        add("## Active incidents")
        add("")
        for inc in incidents:
            add(f"- **{inc.get('title')}** (status: {inc.get('status')}, started {inc.get('started_at')})")
        add("")

    # -- agent contributions ------------------------------------------------------
    agent_nodes = [n for n in nodes if n.source_adapter.startswith("agent:")]
    agent_edges = [
        e for e in edges if str(e.attrs.get("source_adapter", "")).startswith("agent:")
    ]
    if agent_nodes or agent_edges:
        add("## Agent-contributed knowledge")
        add("")
        add("Added by AI agents from docs/code the scanners can't parse (all INFERRED, evidence-backed):")
        add("")
        for node in agent_nodes:
            who = node.source_adapter.split(":", 1)[-1]
            ev = redact_text(node.evidence[0]) if node.evidence else ""
            add(f"- **{node.name}** ({node.type}) — by {who}: {ev}")
        for edge in agent_edges:
            who = str(edge.attrs.get("source_adapter", "agent:?")).split(":", 1)[-1]
            ev = redact_text(edge.evidence[0]) if edge.evidence else ""
            add(f"- `{edge.source}` —{edge.relation.value}→ `{edge.target}` — by {who}: {ev}")
        add("")

    # -- uncertainty ------------------------------------------------------------
    uncertain = [
        n for n in nodes
        if n.confidence in (Confidence.INFERRED, Confidence.AMBIGUOUS) and n.origin != Origin.DERIVED
    ]
    if uncertain:
        add("## Inferred or uncertain")
        add("")
        add("These exist in the graph from indirect evidence only:")
        add("")
        for node in sorted(uncertain, key=lambda n: n.name)[:20]:
            evidence = redact_text(node.evidence[0]) if node.evidence else "no evidence recorded"
            add(f"- **{node.name}** ({node.type}, {node.confidence.value}): {evidence}")
        add("")

    add("---")
    add("Artifacts: `infra.html` (interactive map), `infra.graph.json` (machine-readable graph), "
        "`fingerprint.json`, `access.json`, `runtime-state.json`.")
    return redact_text("\n".join(lines) + "\n")
