"""Renderers: ViewSpec → HTML, Markdown, or terminal output."""

from __future__ import annotations

import re
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from cirdan.access.redaction import redact_obj
from cirdan.ui.view_spec import ViewSpec

_TEMPLATES = Path(__file__).parent / "templates"
_env = Environment(loader=FileSystemLoader(_TEMPLATES), autoescape=select_autoescape(["html"]))


def render_html(spec: ViewSpec) -> str:
    clean = ViewSpec.model_validate(redact_obj(spec.model_dump()))
    return _env.get_template("view.html.j2").render(spec=clean)


def render_markdown(spec: ViewSpec) -> str:
    spec = ViewSpec.model_validate(redact_obj(spec.model_dump()))
    lines = [f"# {spec.title}", "", f"_{spec.view_type} · generated by Cirdan at {spec.generated_at}_", ""]
    for c in spec.components:
        if c.title:
            lines += [f"## {c.title}", ""]
        data = c.data
        if c.type == "SummaryCard":
            if data.get("text"):
                lines += [data["text"], ""]
            for label, value in (data.get("facts") or {}).items():
                lines.append(f"- **{label}:** {value}")
            lines.append("")
        elif c.type in ("StateTable", "LogClusterTable", "MetricChart", "ActionPanel"):
            if c.type == "ActionPanel":
                columns = ["Action", "Description", "Command"]
                rows = [
                    [a["name"] + (" ⚠ writes" if a.get("writes") else ""), a["description"], f"`{a['command']}`"]
                    for a in data.get("actions", [])
                ]
            else:
                columns, rows = data.get("columns", []), data.get("rows", [])
            lines.append("| " + " | ".join(columns) + " |")
            lines.append("|" + "---|" * len(columns))
            for row in rows:
                lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
            lines.append("")
        elif c.type == "IncidentTimeline":
            for entry in data.get("entries", []):
                lines.append(f"- **{entry.get('ts', '')}** — {entry.get('label', '')}: {entry.get('detail', '')}")
            lines.append("")
        elif c.type in ("TopologyGraph", "DependencyGraph"):
            nodes = data.get("nodes", [])
            edges = data.get("edges", [])
            lines.append(f"{len(nodes)} nodes, {len(edges)} edges (see the HTML view for the interactive map):")
            lines.append("")
            for e in edges[:60]:
                lines.append(f"- `{e['source']}` —{e['relation']}→ `{e['target']}`")
            lines.append("")
        elif c.type in ("AccessReport", "Markdown"):
            lines += ["```", data.get("text", "").rstrip(), "```", ""]
    return "\n".join(lines) + "\n"


def render_terminal(spec: ViewSpec, console: Console) -> None:
    spec = ViewSpec.model_validate(redact_obj(spec.model_dump()))
    console.print(Panel(f"[bold]{spec.title}[/bold]\n[dim]{spec.view_type} · {spec.generated_at}[/dim]"))
    for c in spec.components:
        data = c.data
        if c.type == "SummaryCard":
            body = data.get("text", "")
            facts = "  ".join(f"[dim]{k}:[/dim] [bold]{v}[/bold]" for k, v in (data.get("facts") or {}).items())
            console.print(Panel((body + "\n" + facts).strip(), title=c.title or None))
        elif c.type in ("StateTable", "LogClusterTable", "MetricChart"):
            table = Table(title=c.title or None)
            for col in data.get("columns", []):
                table.add_column(str(col))
            for row in data.get("rows", []):
                table.add_row(*[str(cell) for cell in row])
            console.print(table)
        elif c.type == "ActionPanel":
            table = Table(title=c.title or "Available actions")
            for col in ("Action", "Description", "Command"):
                table.add_column(col)
            for a in data.get("actions", []):
                name = a["name"] + (" [red]⚠ writes[/red]" if a.get("writes") else "")
                table.add_row(name, a["description"], a["command"])
            console.print(table)
        elif c.type == "IncidentTimeline":
            for entry in data.get("entries", []):
                style = "red" if entry.get("severity") == "critical" else "yellow"
                console.print(f"[{style}]●[/{style}] [dim]{entry.get('ts', '')}[/dim] "
                              f"[bold]{entry.get('label', '')}[/bold] — {entry.get('detail', '')}")
            if not data.get("entries"):
                console.print("[dim]No incidents recorded.[/dim]")
        elif c.type in ("TopologyGraph", "DependencyGraph"):
            nodes, edges = data.get("nodes", []), data.get("edges", [])
            console.print(f"[dim]{len(nodes)} nodes, {len(edges)} edges — open the HTML view for the map.[/dim]")
        elif c.type in ("AccessReport", "Markdown"):
            console.print(data.get("text", ""))


def view_slug(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug or "view"
